CASMPET-6403 upgrade to new postgres
Cray-HPE/cray-nls-charts pull request #38
Opened 2023-03-14 14:45 UTC by dzou-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-03-14 15:26 UTC, bo-quan approved these changes

2023-03-14 20:13 UTC, bo-quan requested changes
As we're targeting this for CSM 1.5 release, we will need to create a new directory under "charts" according to recommendations from HMS team.

2023-03-15 15:31 UTC, dzou-hpe commented
> As we're targeting this for CSM 1.5 release, we will need to create a new subdir under "charts" (i.e., leaving "v2.0" subdir for CSM 1.4 release).

@bo-quan i am not sure why we need to create a new folder for a new release ... can't we just use git tags? plus why v2.0 is 1.4 ... cause i don't know what to call it for 1.5 ... v3? v2.1? 

IMO, i might have missed something here tho, we should just use one folder for all release versions. especially Chart.yaml has a version and release is based on that. So if we version 1.5 release as 1.5.x, whenever we need to patch 1.4 stuff, we can just branch off latest of 1.4 and release 1.4.x+1 

Maybe this is some team decision on how to manage charts>

2023-03-28 19:12 UTC, bo-quan commented
Replaced with another PR.

2023-03-28 19:12 UTC, closed without merging